force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Cart Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Shopping_Cart__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shopping Cart</label>
    <referenceTo>Shopping_Cart__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Quantity__c *  Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <formula>Book__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>OrderC</label>
    <nameField>
        <displayFormat>ON-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrdersC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>OrdersC</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>UPI (Unified Payments Interface)</fullName>
            </value>
            <value>
                <fullName>Google Pay</fullName>
            </value>
            <value>
                <fullName>Apple Pay</fullName>
            </value>
            <value>
                <fullName>Amazon Pay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Shopping_Cart__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shopping Cart</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Shopping_Cart__c.Contact__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contact__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Shopping_Cart__c</referenceTo>
    <relationshipLabel>OrdersC</relationshipLabel>
    <relationshipName>OrdersC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <label>Shopping Cart</label>
    <nameField>
        <label>Shopping Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shopping Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shopping_Cart__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shopping Carts</relationshipLabel>
    <relationshipName>Shopping_Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shopping_Cart__c/fields/Cart_Status__c.field-meta.xml
<CustomField>
    <fullName>Cart_Status__c</fullName>
    <label>Cart Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shopping_Cart__c/fields/Cart_Total__c.field-meta.xml
<CustomField>
    <fullName>Cart_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cart Total</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shopping_Cart__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shopping Carts</relationshipLabel>
    <relationshipName>Shopping_Carts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderController.cls
public with sharing class OrderController {

    public static User currentUser = [SELECT Contact.AccountId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
    public static Id contactId = currentUser.ContactId;
    public static Id accountId = currentUser.Contact.AccountId;


    @AuraEnabled(cacheable=true)
    public static List<Order__c> getOrders() {
        return [SELECT Id, Name, Order_Date__c, Status__c, Total_Amount__c, Shopping_Cart__c 
                FROM Order__c 
                WHERE Contact__c = :contactId  ORDER BY Order_Date__c DESC] ;
    }

    @AuraEnabled
    public static List<Cart_Item__c> getCartItemsByShoppingCart(Id shoppingCartId) {
        return [SELECT Id, Book__r.Name, Quantity__c,Unit_Price__c, Total_Price__c 
                FROM Cart_Item__c 
                WHERE Shopping_Cart__c = :shoppingCartId];
    }



    @AuraEnabled
    public static String createOrderWithPayment(Decimal amount, Id bookId, Decimal quantity) {
        try {
            List<Shopping_Cart__c> carts = [
                SELECT Id, Cart_Total__c 
                FROM Shopping_Cart__c 
                WHERE Account__c = :accountId 
                AND Cart_Status__c = 'Active' 
                LIMIT 1
            ];
            
            if (carts.isEmpty()) {
                return 'No active shopping cart found.';
            }
    
            Shopping_Cart__c cart = carts[0];
    
            Contact contact = [
                SELECT Id, Name, Email 
                FROM Contact 
                WHERE Id = :contactId 
                LIMIT 1
            ];
    
            Stripe_Configuration__mdt stripeConfig = [
                SELECT Secret_Key__c 
                FROM Stripe_Configuration__mdt 
                LIMIT 1
            ];
    
            if (stripeConfig == null || String.isEmpty(stripeConfig.Secret_Key__c)) {
                return 'Stripe secret key not configured.';
            }
    
            String stripeSecretKey = stripeConfig.Secret_Key__c;
    
            String endpoint = 'https://api.stripe.com/v1/charges';
            HttpRequest req = new HttpRequest();
            req.setEndpoint(endpoint);
            req.setMethod('POST');
            req.setHeader('Authorization', 'Bearer ' + stripeSecretKey);
            req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
    
            String body = 'amount=' + String.valueOf(amount * 100) + '&currency=USD&source=tok_visa';
            req.setBody(body);
    
            Http http = new Http();
            HttpResponse res = http.send(req);
    
            Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            String paymentStatus = (String) responseMap.get('status');
            String returnMessage = '';
    
            if (res.getStatusCode() == 200 && paymentStatus == 'succeeded') {
                returnMessage = 'success';
    
                cart.Cart_Status__c = 'Converted';
                update cart;
    
                if (bookId != null && quantity != 0) {
                    Cart_Item__c cartItem = new Cart_Item__c();
                    cartItem.Book__c = bookId;
                    cartItem.Quantity__c = quantity;
                    cartItem.Shopping_Cart__c = cart.Id;
                    insert cartItem;
                }
    
                Order__c order = new Order__c();
                order.Account__c = accountId;
                order.Contact__c = contactId;
                order.Total_Amount__c = amount;
                order.Shopping_Cart__c = cart.Id;
                order.Status__c = 'Confirmed';
                order.Order_Date__c = System.now();
                insert order;
    
                Payment__c newPayment = new Payment__c();
                newPayment.Account__c = accountId; 
                newPayment.Contact__c = contactId; 
                newPayment.Payment_Method__c = 'Credit Card';
                newPayment.Payment_Status__c = 'Completed';
                newPayment.OrderC__c = order.Id;
                insert newPayment;
    
                Shopping_Cart__c newCart = new Shopping_Cart__c(
                    Account__c = accountId,
                    Contact__c = contactId,
                    Cart_Status__c = 'Active',
                    Cart_Total__c = 0
                );
                insert newCart;
    
            } else {
                returnMessage = 'error';
            }
    
            return returnMessage;
    
        } catch (Exception e) {
            return 'error';
        }
    }
    

}